### ISSUE TITLE
libpng 1.6.20 sourceforge URL has moved

### ISSUE THREAD

**Issue by danzel** [mapbox/mason#207]
It is now down a dir in older-releases/

https://sourceforge.net/projects/libpng/files/libpng16/

**Comment by danzel** [comment]
Will need to pull the updated mason in to mapbox-gl-native

**Comment by springmeyer** [comment]
This was fixed in the key libpng packages by pointing to the  `old-releases` url like: https://github.com/mapbox/mason/blob/1319207a0e88eb842156ca027876be3770aca587/scripts/libpng/1.6.25/script.sh#L15. We unfortuntely will keep hitting this since png moves releases frequently. Tracking a way to avoid at #376
