### ISSUE TITLE
Boost 1.62

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mason#264]
[Boost 1.62 was released on September 28](http://www.boost.org/users/history/version_1_62_0.html). We should package it.

/cc @springmeyer

**Comment by springmeyer** [comment]
👍  Will queue up a PR adding boost 1.62 later today. /cc @kkaefer

**Comment by kkaefer** [comment]
Not urgent, just ticketing

**Comment by daniel-j-h** [comment]
I think this ticket can be closed as Boost 1.62 was imported in https://github.com/mapbox/mason/issues/282. Also there is now already Boost 1.63 ([changelog](http://www.boost.org/users/history/version_1_63_0.html)) which we might want to import.

- http://lists.boost.org/boost-users/2016/12/87009.php
- http://lists.boost.org/boost-users/2016/12/87010.php

**Comment by daniel-j-h** [comment]
For the record since I just stumbled over it: seems like Boost 1.62 needs at least CMake 3.7+ and Boost 1.63 is not yet supported with CMake but a PR is on the way:

- https://github.com/Kitware/CMake/commit/a997cac8323dc1764e092b8691857dd9af70956e
- https://gitlab.kitware.com/cmake/cmake/merge_requests/361

The CMake version in Mason should probably be in sync with the supported Boost versions.

**Comment by springmeyer** [comment]
New ticket to provide latest boost 1.63 and latest cmake at https://github.com/mapbox/mason/issues/310
