### ISSUE TITLE
Make linking platform-specific

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mason#290]
As a follow up to https://github.com/mapbox/mason/pull/216: `mason link` currently creates all symlinks in a shared `mason_packages/.link` folder. However, we should instead create `.link` folders per architecture, e.g. `mason_packages/osx-x86_64/.link`.

/cc @daniel-j-h @springmeyer

**Comment by springmeyer** [comment]
Can you say more why this is desirable/required? I created the `link` command specifically so that there would not be any versioned paths and you could safely specify the `mason_packages/.link/` directory and have it work cross-platform. If you want platform-specific paths you can just use `mason prefix` paths. If there is a need for a hybrid that versions by platform but not by package version perhaps that could be a new command?

**Comment by kkaefer** [comment]
When using packages of multiple architectures simultaneously (e.g. various Android architectures, or iOS + macOS), all of those packages will be linked to the same path, but of course they have vastly different libraries. Using a single shared `.link` directory means that you can't e.g. build two Android versions side by side, or use iOS and macOS at the same time.

**Comment by springmeyer** [comment]
per chat:

  - the only utility to the link command is when collapsing all paths
  - so, creating a linked directory of versioned paths is pointless
  - going to close this issue therefore, we'll rather consider keeping the `mason link` command as-is and deprecating in the future: #377
