### ISSUE TITLE
Package osrm-tag-rewriter project

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/mason#440]
We should package our exit signage re-writing tool

https://github.com/mapbox/rewrite-exit-destination-signage

It's already masonized and can be built with mason deps only.

**Comment by springmeyer** [comment]
:+1 @daniel-j-h - I see that you've given a refresh to the build over at https://github.com/mapbox/rewrite-exit-destination-signage/commit/92defc2020595bd9cad52e5b26c081209ddfb631. Can you tag a release as well?

> It's already masonized and can be built with mason deps only.

👍  Only concern is that because `rewrite-exit-destination-signage` depends on mason itself for deps, to be careful that the script.sh does not clobber the mason that is doing the packaging. 

As far as packaging in mason, are you able to do this or do you need help?

**Comment by daniel-j-h** [comment]
Tagged https://github.com/mapbox/rewrite-exit-destination-signage/releases/tag/v1.0.0

**Comment by springmeyer** [comment]
done in #483
