### ISSUE TITLE
cairo-1.14.8 build fails on Debian stretch i386

### ISSUE THREAD

**Issue by tpikonen** [mapbox/mason#490]
Building cairo-1.14.8 with mason fails on IA32 Debian stretch and gcc version 6.3.0. 

autogen / configure fails to link programs with pthread and disables threading which apparently does not go well with the rest of the cairo build.

The build succeeds when "-Wmissing-declarations" is removed from $CAIRO_CFLAGS_DEFAULTS.

**Comment by springmeyer** [comment]
👍  on removing `-Wmissing-declarations`. That is there since the x86_64 build with clang++ enabled it by default. Can you create a PR with that removed?

Note:  while this problem sounds minor and easily fixable we don't normally test on 32 bit (IA32) so there may be some/a lot? of other problems lurking.

**Comment by tpikonen** [comment]
Ok, created PR #491.
