### ISSUE TITLE
Sudo false everywhere

### ISSUE THREAD

**Issue by ljbade** [mapbox/mason#58]
All mason builds should use `sudo: false` as they are noticeably faster.

**Comment by ljbade** [comment]
I talked to Travis and it seems you can request apt packages to be whitelisted so they can be installed on the `sudo: false` machines.

To use the undocumented/stop-gap feature (they say until they figure out a better way to handle `sudo` you add these lines to `.travis.yml`
```
addons:
  apt_packages:
    - xutils-dev
```

In this case the `xutils-dev` package will be installed on the machine for you.

The list of whitelisted packages can be found at https://github.com/travis-ci/apt-package-whitelist

/cc @springmeyer

**Comment by ljbade** [comment]
This allowed me to speed up the openssl branch a lot.

**Comment by springmeyer** [comment]
Yes, :+1: we definitely want to use sudo:false wherever possible. That whitelist group is good to know about, but pretty limited. For small build deps, like ragel (https://github.com/mapbox/mason/tree/ragel-6.9), I think we should just package the dependency ourselves (like I've done) with mason instead of waiting to request a whitelist. For large packages with lots of shared lib dependencies like xutils-dev or x11 stuff, whitelisting seems like the only viable option.

**Comment by springmeyer** [comment]
Closing this as there are no further actions. Recently the whitelisted packages have grown in numbers, which is great. Travis devs are not keeping up with requests atm (https://github.com/travis-ci/travis-ci/labels/apt-whitelist) but hopefully that will improve.
