### ISSUE TITLE
don't put -std=c++11 into CXXFLAGS

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mason#91]
https://github.com/mapbox/mason/blob/c842ce48b5d4d4a230bcebbedf658b4efcd81ae4/mason.sh#L187

In mapbox-gl-native, this makes its way into the build commands via [toolchain.sh](https://github.com/mapbox/mapbox-gl-native/blob/2b633cc51cd44be3f0224f0b105b18f0a3d7d657/scripts/android/toolchain.sh#L24-24) and [defaults.mk](https://github.com/mapbox/mapbox-gl-native/blob/2b633cc51cd44be3f0224f0b105b18f0a3d7d657/config/defaults.mk#L34-34) and causes errors because we want `-std=c++14` now.

Why is mason.sh setting this?

**Comment by jfirebaugh** [comment]
cc @springmeyer @kkaefer @ljbade

**Comment by jfirebaugh** [comment]
@ljbade removed this in d67ecce41c484af9471aed9cf9cc5084191ecaa5

**Comment by springmeyer** [comment]
> Why is mason.sh setting this?

Because the intention was to target c++11. And my assumption is that even for c++ deps that don't have a hard requirement on c++11 (like boost) you want to ask to compile with it to avoid the rare ABI issues that can result from non-c++11 compiled deps being linked by a c++11 compiled app. And because it allows the compiler to turn on some optimizations around move semantics. 

Makes sense to remove to be able to target c++14. My only question then is do we add `-std=c++11` or `-std=c++14` back per dependency if not set globally?
